### ISSUE TITLE
Using absolute paths with @import for .less files results in exception

### ISSUE THREAD

**Issue by nayanshah** [dotless/dotless#503]
The scenario is for consuming external components which are outside the "source" folder.

e.g. contents of Z:\less\B.less:
``
@import "Z:\external\A.less";
``

dotless.compiler.exe B.less B.css
```
[Compile]
Z:\less\B.less -> Z:\less\B.css
[FAILED]
Compilation failed: You are importing a file ending in .less that cannot be found [Z:\external\A.less].
   at dotless.Core.Importers.Importer.Import(Import import) in c:\projects\dotless\src\dotless.Core\Importers\Importer.cs:line 227
   at dotless.Core.Parser.Tree.Import.GetImportAction(IImporter importer) in c:\projects\dotless\src\dotless.Core\Parser\Tree\Import.cs:line 88
   at dotless.Core.Parser.Tree.Import.Evaluate(Env env) in 
```

**Comment by nayanshah** [comment]
This probably got introduced by 9fe520c8. 

Potential fix could be to just check if IsPathRooted returns true for lessPath before prefixing CurrentDirectory.
